---
title: "CRISP-DM Project 1 Writeup"
author: "Ben Jaeger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
    number_sections: TRUE
    keep_tex: FALSE
    keep_md: FALSE
  html_document:
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Business Understanding

## Determine Business Objectives

Background  
Business Objectives  
Business Success Criteria  

## Assess Situation

Inventory of Resources  
Requirements, Assumptions, and Constraints  
Risks and Contingencies
Terminology
Costs and Benefits

## Determine Data Mining Goals

Data Mining Goals
Data Mining Success Criteria

## Produce Project Plan

Project Plan
Initial Assessment of Tools and Techniques

\newpage

# Data Understanding

## Collect Initial Data

Initial Data Collection Report

## Describe Data

Data Description Report

## Explore Data

Data Exploration Report

## Verify Data Quality

Data Quality Report


\newpage

# Data Preparation

## Select Data

Rationale for Inclusion/Exclusion

## Clean Data

Data Cleaning Report

## Construct Data

Derived Attributes
Generated Records

## Integrate Data

Merged Data

## Format Data

Reformatted Data

## Dataset

Dataset Description

\newpage

# Modeling

## Select Modeling Techniques

Modeling Technique
Modeling Assumptions

## Generate Test Design

Test Design

## Build Model

Parameter Settings
Models
Model Descriptions

## Assess Model

Model Assessment
Revised Parameter Settings

\newpage

# Evaluation

## Evaluate Results

Assessment of Data Mining Results w.r.t. Business Success Criteria
Approved Models

## Review Process

Review of Process

## Determine Next Steps

List of Possible Actions
Decision

\newpage

# Deployment

## Plan Deployment

Deployment Plan

## Plan Monitoring and Maintenance

Monitoring and Maintenance Plan

## Produce Final Report

Final Report
Final Presentation

## Review Project

Experience Documentation
